PHP 8.1 interfaces
adbario/php-dot-notation pull request #22
Opened 2021-10-18 11:27 UTC by nicoorfi

Hi, this fixes some issues in PHP 8.1 with the `ArrayAccess`, `Countable`, `IteratorAggregate`, `JsonSerializable` interfaces.

2021-12-01 13:11 UTC, tdgroot requested changes

2021-12-01 13:11 UTC, tdgroot commented on src/Dot.php
> +    public function offsetExists($key):bool
```suggestion
    public function offsetExists($key): bool
```

2021-12-01 14:52 UTC, tdgroot approved these changes

2021-12-28 11:44 UTC, Ethorsen commented
Any chance to see these changes being released soon?

2022-01-31 10:02 UTC, ozgurg commented
@adbario Any update?

2022-01-31 10:10 UTC, ozgurg approved these changes

2022-02-07 14:04 UTC, fernando-rivas-smtp approved these changes

2022-02-23 16:56 UTC, mxdpeep commented
still not merged into the main branch = PHP 8.1 upgrade blocker in my projects

2022-03-13 20:26 UTC, nicojmb commented
Waiting to new release to upgrade to PHP8.1

2022-03-14 06:52 UTC, mxdpeep commented
I have fixed the issue myself and I keep overwriting the Dot.php file.

Filip Oščádal
CEO mxd.cz

On Sun, Mar 13, 2022, 21:26 Nicolás Martinez ***@***.***>
wrote:

> Waiting to new release to upgrade to PHP8.1
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/adbario/php-dot-notation/pull/22#issuecomment-1066175800>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAASMXRM5DFIIFQO4IEAA7DU7ZFP3ANCNFSM5GGMVK3Q>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-03-25 00:49 UTC, adbario approved these changes
Thanks for the PR and apologies for the delayed response. Type declarations need a couple of changes, but I'll sort them out while adding PHP 8.1 to CI.

2022-03-25 00:49 UTC, merged

2022-03-25 10:02 UTC, mxdpeep commented
Thanx 🍀❤️

Filip Oščádal 🍀📱

On Fri, Mar 25, 2022, 01:50 Riku Särkinen ***@***.***> wrote:

> Merged #22 <https://github.com/adbario/php-dot-notation/pull/22> into 2.x.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/adbario/php-dot-notation/pull/22#event-6303835079>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAASMXROFPF5QCRURTNWE3TVBUEUBANCNFSM5GGMVK3Q>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>